### ISSUE TITLE
canvas rotate

### ISSUE THREAD

**Issue by mcrisci** [jhuckaby/webcamjs#53]
Hi,

thank you for this script : it is perfect for my needs and work very well

but how can i rotate the preview canvas? and so snap image that are rotated ... 

some users of my website use external webcam in portrait mode, so a 90 degree rotation could be useful, maybe passing a parameter, sorry i'am not so good in js, i try to modify your code but i didn't come up with anything 

hope you can help

**Comment by jhuckaby** [comment]
Well, there's no built-in feature for rotating the live preview, but you may be able to get it to work using CSS transforms:

```css
#your_element_id {
    -webkit-transform: rotate(90deg); 
    -webkit-transform-origin: 50% 50%;
    transform: rotate(90deg); 
    transform-origin: 50% 50%;
}
```

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transforms

Good luck!

- Joe
