### ISSUE TITLE
Option to flip webcam image

### ISSUE THREAD

**Issue by thenikso** [jhuckaby/webcamjs#58]
I'd like to flip the webcam image so that it would act like a mirror (ie: if I move my head to the right it should follow on the screen instead of going the other way).

Is this already possible?

Thanks!

**Comment by jhuckaby** [comment]
You can achieve this using CSS transforms:

```css
#my_camera {
	-moz-transform: scaleX(-1);
	-o-transform: scaleX(-1);
	-webkit-transform: scaleX(-1);
	transform: scaleX(-1);
	filter: FlipH;
	-ms-filter: "FlipH";
}
```

Here is a demo:
http://pixlcore.com/demos/webcamjs/demos/flip.html

Good luck!

- Joe
